{% set name = "basic-modeling-interface" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/bmi-forum/bmi-python

requirements:
  build:
    - python
  run:
    - python

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - basic_modeling_interface

about:
  home: http://bmi-python.readthedocs.io/en/latest
  license: MIT
  license_file: LICENSE
  summary: The Basic Model Interface (BMI) defines an interface for
    converting a standalone model into an integrated modeling
    framework component.
  dev_url: https://github.com/bmi-forum/bmi-python
