language: generic
os:
  - linux
  - osx
env:
  matrix:
    - TRAVIS_PYTHON_VERSION="2.7"
    - TRAVIS_PYTHON_VERSION="3.*"
  global:
    - secure: "XcWzCdiADCPN2tNLKD65CEs4fwkTDq/hp5Sgmr+d0I2ZuMKjc2CeoewaYvVE6UFAihdx8PbjskJIEcEwG34Fnsb7ogS2Dd9pNVWQ+w0pgvTxTRTK6Pr9KPV4keCJ43hIXtj3MexJcNrski5ODnQSNkceFlum6mqkKDeqyhWG+Ze6DgsXeArBZOqsIkw8QPLYiMMNMULsqVW0C2+yrO2wyWJi+jZZD+0MXE7EiOpNqC1bYAwJbOeGQPEWzhXutRRQ3VqG/6/c2b1isuj8bRsdJpfeCKnzcoIJmuO84EJ6GQUEx0oAjK34JQixfPNrnnJcyYD9Gkffj1+9PfltvcvLDTGHb+ZY6r+RsUSf7mIomilczcQ4Of4/XAKXtoeylLN7QVdwjLLm4s3ucJqnt+ejbg9I8KKEFPpTto4m9K/vfkq30iQr+HcZGtUHCr8Zgc9RmKInc+w7hXvquGaKjV21KUttdEObgj0PGv4XWxvdc3Dt6uGwcv07XNkiKefACsNhV2HdD/wbAjRI+BeR/x6Bf0hTH9Ek7wzuw13aSRuQQUy59nPpKzFfz9wzSqSLsgbuDXhsWw43QxA+3x5XNKvsMQowkp4yphbRR1HJNdHrSRP6Lvmj4rtqQ9GxYsBbStWuGL3bRXtDrbpuPaoc8155uWA68xbSDhQ/xYDDS3c/5dQ="
sudo: false
before_install:
  - echo "Build on $TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev"; fi
  - source .ci/travis/install_python.sh
  - conda info -a
install:
  - conda build ./recipe -c csdms-stack -c conda-forge --old-build-string
after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
